@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!define RECTANGLE class
!define INTERFACE interface

rectangle "module theClient" as theClientModule {
    package "com.myorg.client" {
        RECTANGLE ClientApp
    }
}

rectangle "module theFirstAPI" as theFirstApiModule {
    package "com.myorg.first" {
        RECTANGLE FirstAPI
        INTERFACE Helper
    }
    package "com.myorg.impl" {
        RECTANGLE HelperImpl
    }
}
    note right of first
      exports com.myorg.first
    end note
    note top of impl
      opens com.myorg.impl
    end note

ClientApp --> FirstAPI : calls
ClientApp --> HelperImpl : uses
HelperImpl ..|> Helper : implements
@enduml